#!/bin/sh

set -eu

BASE_DIR="${1}"

classes_in_file() {
	local f="${1}"

	pcregrep -o3 '^\s*(public|private|)\s+(class|enum)\s+([a-zA-Z]+)(<([a-zA-Z],\s*)*[a-zA-Z]>)?\s' "${f}"
}

generated() {
	for f in "${BASE_DIR}"/*.java
	do
		main_class="$(classes_in_file "${f}" | head -n 1)"
		echo "${main_class}.class"

		if [ "$(classes_in_file "${f}" | wc -l)" -gt 1 ]
		then
			echo "${main_class}\$1.class"
		fi

		classes_in_file "${f}" | tail -n +2 | sed "s|^|${main_class}\$|; s|\$|.class|"
	done
}

inputs="$(echo "${BASE_DIR}"/*.java | xargs -n 1 basename | xargs echo)"
echo ": ${inputs} |> !javac |> $(generated | xargs echo)"
